version: '3'
services:
  red-spacecraft:
    image: red-spacecraft:latest
    container_name: 'red-spacecraft'
    hostname: red-spacecraft
    environment:
      NODE_ENV: production
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - net
    ports:
      - '3001:3001'
    restart: always
networks:
  net:
    driver: bridge
