name: Deploy to Staging

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: red-spacecraft
      url: https://red-spacecraft.herokuapp.com
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "red-spacecraft"
          heroku_email: "fahrizal.maruf@gmail.com"
          usedocker: false
