name: Testing

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare node_modules cache
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Using NodeJS environment
        uses: actions/setup-node@v1
        with:
          node-version: "17"
      - name: Installing dependencies
        run: yarn install
      - name: Running Test
        run: yarn test --watchAll=false
